const ActionTypes = {
    SET_CANVAS_SIZE: 'SET_CANVAS_SIZE',
    CHANGE_SHAPE_COLOR: 'CHANGE_SHAPE_COLOR',
    CHANGE_BACKGROUND_COLOR: 'CHANGE_BACKGROUND_COLOR',
    ADD_TO_PALETTE: 'ADD_TO_PALETTE'
}

export default ActionTypes;