const ActionTypes = {
    SET_CANVAS_SIZE: 'SET_CANVAS_SIZE',
    CHANGE_CANVAS_SCALE: 'CHANGE_CANVAS_SCALE',
    CHANGE_SHAPE_COLOR: 'CHANGE_SHAPE_COLOR',
    CHANGE_BACKGROUND_COLOR: 'CHANGE_BACKGROUND_COLOR',
    ADD_TO_PALETTE: 'ADD_TO_PALETTE',
    REPLACE_PALETTE: 'REPLACE_PALETTE',
    CHANGE_SHAPE_TYPE: 'CHANGE_SHAPE_TYPE',
    CHANGE_SHAPE_WIDTH: 'CHANGE_SHAPE_WIDTH',
    CHANGE_SHAPE_HEIGHT: 'CHANGE_SHAPE_HEIGHT',
    CHANGE_SHAPE_RADIUS: 'CHANGE_SHAPE_RADIUS',
    ADD_SHAPE_TO_CANVAS: 'ADD_SHAPE_TO_CANVAS',
    SELECT_SHAPE: 'SELECT_SHAPE'
}

export default ActionTypes;